genoome/accounts/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.core.urlresolvers import reverse_lazy
from django.conf.urls import url
from django.contrib.auth.views import login, logout, password_reset, password_reset_done, password_reset_confirm, \
    password_reset_complete
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

from . import views
from .forms import SignInForm
from .forms import PasswordResetForm

urlpatterns = [
    url(r'^logout/$', logout, {'next_page': reverse_lazy('landing_page')}, name='logout'),
    url(r'^signin/$', login, {'template_name': 'signin.html', 'authentication_form': SignInForm}, name='signin'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^password-reset/$', password_reset, kwargs={'password_reset_form': PasswordResetForm,
                                                      'from_email': '"genoomy.com team" <noreply@genoomy.com>',
                                                      'post_reset_redirect': 'accounts:password_reset_done',
                                                      'html_email_template_name': 'registration/password_reset_email.html',
                                                      'email_template_name': 'registration/password_reset_email.txt'},
        name='password_reset'),
    url(r'^password-reset/done/$', password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        password_reset_confirm, kwargs={'post_reset_redirect': 'accounts:password_reset_complete'}, name='password_reset_confirm'),
    url(r'reset/complete/$', password_reset_complete, name='password_reset_complete'),
    url(r'^activate/$', views.AccountActivateView.as_view(), name='activate_account'),
    url(r'^contact/$', views.ContactFormView.as_view(), name='contact'),
    url(r'^signup-success/$', views.SignupSuccessView.as_view(), name='signup_success'),
    url(r'^save-email/$', views.UserCreateWithEmail.as_view(), name='create_with_email'),
    url(r'^save-email-succes/$', views.UserCreateSuccess.as_view(), name='create_with_email_success'),
    url(r'^profile/$', csrf_exempt(login_required(views.UserProfileView.as_view(), login_url='/accounts/signin')), name='profile'),
    url(r'^disable/$', login_required(views.AccountDisableView.as_view()), name='disable')
    # url(r'^view/$', views.special_case_2003),
]

genoome/disease/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.core.urlresolvers import reverse_lazy

from . import views

urlpatterns = [
    url(r'^upload/$', views.UploadGenome.as_view(), name='upload_genome'),
    url(r'^upload-success/(?P<pk>[0-9]+)/$', csrf_exempt(login_required(views.UploadGenomeSuccessView.as_view(), login_url=reverse_lazy('accounts:signin'))), name='upload_success'),
    url(r'^browse/$', login_required(views.DisplayGenomeResult.as_view(), login_url=reverse_lazy('accounts:signin')), name='browse_genome'),
    url(r'^landing-genome-data/$', views.landing_genome_data, name='landing_json_data'),
    url(r'^description/(?P<pk>[0-9]+)/$', views.allele_description, name='description'),
    url(r'^payment-status/$', csrf_exempt(views.PaymentStatusView.as_view()), name='payment_status'),
]

genoome/genoome/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.contrib.flatpages.views import flatpage
from django_markdown import flatpages

from accounts.views import LandingView
from disease.views import upload_progress

admin.autodiscover()
flatpages.register()

urlpatterns = patterns('',
    url(r'^$', LandingView.as_view(), name='landing_page'),
    url(r'^faq/$', TemplateView.as_view(template_name='faq.html'), name='faq'),
    url(r'^genotype-description', flatpage, name='genotype_description'),

    # Examples:
    # url(r'^$', 'genoome.views.home', name='home'),
    url(r'^update-progress/$', upload_progress, name='upload_progress'),
    url(r'^disease/', include('disease.urls', namespace='disease')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^payments/', include('payments.urls', namespace='payments')),
    url(r'^23andme/', include('twentythree.urls', namespace='23andme')),

    url('^markdown/', include('django_markdown.urls')),


    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

# Uncomment the next line to serve media files in dev.
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

genoome/accounts/models.py
from django.contrib.auth import models as auth_models
from django.core import validators
from django.core.files.storage import FileSystemStorage
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from disease.files_utils import get_genome_dirpath

import time

storage = FileSystemStorage()


class GenoomyAbstractUser(auth_models.AbstractBaseUser, auth_models.PermissionsMixin):
    """
    Shameless copy of django auth model which sole purpose is to increase max_length of some fields
    """
    username = models.CharField(_('username'), max_length=80, unique=True,
        help_text=_('Required. 80 characters or fewer. Letters, digits and '
                    '@/./+/-/_ only.'),
        validators=[
            validators.RegexValidator(r'^[\w.@+-]+$',
                                      _('Enter a valid username. '
                                        'This value may contain only letters, numbers '
                                        'and @/./+/-/_ characters.'), 'invalid'),
        ],
        error_messages={
            'unique': _("A user with that username already exists."),
        })
    first_name = models.CharField(_('first name'), max_length=80, blank=True)
    last_name = models.CharField(_('last name'), max_length=80, blank=True)
    email = models.EmailField(_('email address'), blank=True)
    is_staff = models.BooleanField(_('staff status'), default=False,
        help_text=_('Designates whether the user can log into this admin '
                    'site.'))
    is_active = models.BooleanField(_('active'), default=True,
        help_text=_('Designates whether this user should be treated as '
                    'active. Unselect this instead of deleting accounts.'))
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = auth_models.UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        abstract = True

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        "Returns the short name for the user."
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """
        Sends an email to this User.
        """
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def disable(self):
        """
        Disables user account.
        """
        self.is_active = False
        self.email = self.username = \
            '%s-disabled.%d' % (self.username, time.time())


class GenoomyUser(GenoomyAbstractUser):
    FILES_PER_USER = 1

    class Meta(GenoomyAbstractUser.Meta):
        swappable = 'AUTH_USER_MODEL'

    @property
    def uploaded_files(self):
        files = []
        dirpath = get_genome_dirpath(self)
        if storage.exists(dirpath):
            _, files = storage.listdir(storage.path(dirpath))
        for file in files:
            filename, ext = file.rsplit('.', 1)
            if not filename.endswith('_processed'):
                yield file

    @property
    def can_upload_files(self):
        files = list(self.uploaded_files)
        can_upload = bool(len(files) < self.FILES_PER_USER)
        return bool(can_upload or (self.is_staff and self.is_active))

genoome/accounts/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from coupons.forms import CouponForm
from coupons.models import Coupon
from django import forms
from django.conf import settings
from django.core.mail import send_mail
from django.core.validators import EMPTY_VALUES
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import PasswordResetForm as AuthPasswordResetForm
from django.utils.translation import ugettext_lazy as _

user_model = get_user_model()


class SignInForm(AuthenticationForm):
    error_messages = {
        'invalid_login': _("Please enter a correct email and password. "
                           "Note that both fields may be case-sensitive."),
        'inactive': _("This account is inactive. You need activation code to login."),
    }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Email'


class EmailUserCreateForm(forms.ModelForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = user_model
        fields = ['email']

    def save(self, commit=True):
        self.instance.username = self.cleaned_data.get('email', '')
        return super().save(commit)


class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta(UserCreationForm.Meta):
        model = user_model
        fields = ('email',)

    def clean_email(self):
        email = self.cleaned_data['email']
        if user_model.objects.filter(username=email).count():
            raise ValidationError('User with this email already exists')

        return email

    def save(self, commit=True):
        self.instance.username = self.cleaned_data.get('email', '')
        user = super().save(commit=commit)
        return user


class ActivateAccountForm(forms.Form):
    email = forms.EmailField()

    def clean_email(self):
        email = self.cleaned_data.get('email', None)
        if not user_model.objects.filter(email=email).exists():
            raise forms.ValidationError(
                "Account does not exist",
                code='no_account')
        return email

    def activate_user(self):
        email = self.cleaned_data['email']
        user = user_model.objects.get(email=email)
        user.is_active = True
        user.save()


class ContactForm(forms.Form):
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)

    def send_email(self):
        user_email = self.cleaned_data['email']
        message = self.cleaned_data['message']
        subject = 'Contact form from {}'.format(user_email)
        send_mail(subject, message, user_email, [settings.EMAIL_HOST_USER], fail_silently=True)

class PasswordResetForm(AuthPasswordResetForm):
    def clean_email(self):
        email = self.cleaned_data['email']
        if not get_user_model().objects.filter(is_active=True, email__iexact=email).exists():
            raise forms.ValidationError('User with given email does not exist.', 'invalid')
        return email

genoome/accounts/views.py
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import get_user_model, login, logout
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import CreateView
from django.views.generic import FormView
from django.views.generic import TemplateView
from django.template.loader import get_template
from django.forms import Form

from accounts.forms import ActivateAccountForm
from accounts.forms import ContactForm
from accounts.forms import EmailUserCreateForm
from accounts.forms import SignUpForm


class UserCreateWithEmail(CreateView):
    template_name = 'save_email.html'
    form_class = EmailUserCreateForm
    model = get_user_model()
    # fields = ('email',)
    success_url = reverse_lazy('accounts:create_with_email_success')

    def form_valid(self, form):
        resp = super().form_valid(form)
        template = get_template('save_email_success.html')
        resp.template = template
        return resp

class UserCreateSuccess(TemplateView):
    template_name = 'save_email_success.html'


class SignUpView(CreateView):
    form_class = SignUpForm
    model = get_user_model()
    success_url = reverse_lazy('accounts:profile')
    template_name = 'signup.html'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        return kwargs

    def form_valid(self, form):
        self.object = form.save()  # User

        # Dirty way to login user
        self.object.backend = 'django.contrib.auth.backends.ModelBackend'
        login(self.request, self.object)

        ctx = {}
        if self.object.is_active:
            ctx['activated'] = True
            messages.success(self.request, 'Your account is now active. You are logged in.')
        return super().form_valid(form)

    def get_template_names(self):
        if self.request.is_ajax():
            return 'signup_modal.html'
        return 'signup.html'


class SignupSuccessView(TemplateView):
    template_name = 'signup_success.html'


class UserProfileView(TemplateView):
    template_name = 'user_profile.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['saved_genome_data'] = self.request.user.uploaded_files
        return ctx

    def post(self, request, *args, **kwargs):
        return self.get(request, *args, **kwargs)

class AccountActivateView(SuccessMessageMixin, FormView):
    template_name = 'activate_account.html'
    form_class = ActivateAccountForm
    success_url = reverse_lazy('accounts:profile')
    success_message = 'Your account is now active.You can no log in.'

    def form_valid(self, form):
        form.activate_user()
        return super().form_valid(form)

class AccountDisableView(SuccessMessageMixin, FormView):
    template_name = 'disable_account.html'
    form_class = Form
    success_url = reverse_lazy('landing_page')
    success_message = 'Your account is now disabled.'

    def form_valid(self, form):
        self.request.user.disable()
        self.request.user.save()
        logout(self.request)

        return super().form_valid(form)

class LandingView(TemplateView):
    template_name = 'landing.html'

class ContactFormView(FormView):
    form_class = ContactForm
    template_name = 'contact.html'
    success_url = reverse_lazy('accounts:contact')

    def form_valid(self, form):
        form.send_email()
        messages.success(self.request, 'Thank you. Your message has been sent.')
        return super().form_valid(form)

genoome/accounts/templates/activate_account.html
{% extends 'base.html' %}

{% block title %}Activate account{% endblock title %}
{% block page_title %}Activate account{% endblock page_title %}

{% block header %}
{% endblock header %}

{% block content %}
    <section class="form section has-pattern">
        <div class="container">

            <div class="row">
                <div class="col-md-6 col-sm-12 col-xs-12 col-md-offset-3">
                    <h1 class="title">Activate account</h1>
                </div>
            </div>

            <div class="row text-center">
                <div class="cnt-form col-md-6 col-sm-12 col-xs-12 col-md-offset-3">

                    {% include 'includes/activate_account_form.html' %}

                </div>
            </div>
        </div>
    </section>
{% endblock content %}

genoome/accounts/templates/contact.html
{% extends 'base.html' %}

{% block title %}Contact{% endblock title %}
{% block page_title %}Contact{% endblock page_title %}

{% block header %}
{% endblock header %}

{% block content %}
    <section class="form section has-pattern">
        <div class="container">

            <div class="row">
                <div class="col-md-6 col-sm-12 col-xs-12 col-md-offset-3">
                    <h1 class="title">Contact</h1>
                    <div class="intro">

                        <p>We’d love to hear from you.</p>
                        <ul class="list-unstyled contact-details">
                            <li><i class="fa fa-envelope"></i><a href="mailto:info@genoomy.com">info@genoomy.com</a></li>
                        </ul>

                    </div>
                </div>
            </div>

            <div class="row text-center">
                <div class="cnt-form col-md-6 col-sm-12 col-xs-12 col-md-offset-3">

                    {% include 'includes/contact_form.html' %}

                </div>
            </div>
        </div>
    </section>
{% endblock content %}

genoome/accounts/templates/disable_account.html
{% extends 'base.html' %}

{% block title %}Disable account{% endblock title %}
{% block page_title %}Disable account{% endblock page_title %}

{% block header %}
{% endblock header %}

{% block content %}
    <section class="form section has-pattern">
        <div class="container">

            <div class="row">
                <div class="col-md-6 col-sm-12 col-xs-12 col-md-offset-3">
                    <h1 class="title">Disable account</h1>
                    <div class="intro">

                        <p>Disabling your account will make all your data inaccessible. This cannot be undone.</p>

                    </div>
                </div>
            </div>

            <div class="row text-center">
                <div class="cnt-form col-md-6 col-sm-12 col-xs-12 col-md-offset-3">

                    <form action="{% url "accounts:disable" %}" method="POST">
                        {% csrf_token %}
                        <div class="form-row">
                            <button class="btn btn-lg btn-danger"><i class="glyphicon glyphicon-remove"></i> Disable account</button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>
{% endblock content %}

genoome/accounts/templates/save_email.html
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title">Leave your email</h4>
</div>
<div class="modal-body">
    {% include "includes/save_email_form.html" %}
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
{#    <button type="button" class="btn btn-primary">Save changes</button>#}
</div>

genoome/accounts/templates/save_email_success.html
{% extends "success_modal.html" %}

{% block modal_title %}
    Success!
{% endblock modal_title  %}

{% block alert_message %}
    Thank you for submission!
{% endblock alert_message %}

genoome/accounts/templates/signin.html
{% extends 'base.html' %}

{% block title %}Login{% endblock title %}
{% block page_title %}Login{% endblock page_title %}

{% block header %}
{% endblock header %}

{% block content %}
    <section class="form section has-pattern">
        <div class="container">

            <div class="row">
                <div class="col-md-6 col-sm-12 col-xs-12 col-md-offset-3">
                    <h1 class="title">Login</h1>
                    <div class="intro">

                        <ul class="list-unstyled contact-details">
                            <li><a href="{% url "accounts:password_reset" %}">Forgot your password?</a></li>
                            <li><a href="{% url "accounts:signup" %}">Don't have an account?</a></li>
                        </ul>

                    </div>
                </div>
            </div>

            <div class="row text-center">
                <div class="cnt-form col-md-6 col-sm-12 col-xs-12 col-md-offset-3">

                    {% include 'includes/signin_form.html' %}

                </div>
            </div>
        </div>
    </section>
{% endblock content %}

{% block modals %}
    <div class="modal fade" id="modal-signup">
        <div class="modal-dialog">
            <div id="modal_content" class="modal-content">
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div>
{% endblock modals %}

genoome/accounts/templates/signup.html
{% extends 'base.html' %}

{% block title %}Register{% endblock title %}
{% block page_title %}Register{% endblock page_title %}

{% block header %}
{% endblock header %}

{% block content %}
    <section class="form section has-pattern">
        <div class="container">

            <div class="row">
                <div class="col-md-6 col-sm-12 col-xs-12 col-md-offset-3">
                    <h1 class="title">Register</h1>
                </div>
            </div>

            <div class="row text-center">
                <div class="cnt-form col-md-6 col-sm-12 col-xs-12 col-md-offset-3">

                    {% include 'includes/signup_form.html' %}

                </div>
            </div>
        </div>
    </section>
{% endblock content %}

genoome/accounts/templates/signup_modal.html
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title">Register</h4>
</div>
<div class="modal-body">
    {% include 'includes/signup_form.html' %}
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
{#    <button type="button" class="btn btn-primary">Save changes</button>#}
</div>

genoome/accounts/templates/signup_success.html
{% extends "base.html" %}

{% block modal_title %}
    Success!
{% endblock modal_title  %}

{% block alert_message %}
    <p>
        Thank you for registering!
        {% if activated %}
            You can now login.
            <script>
                (function(){
                    dataLayer.push({'event': 'UserActivation'});
                    $(document).trigger('reload-page');
                })();
            </script>
        {% else %}
            To login you need activation code first.
        {% endif %}
    </p>
    <script>
        (function(){
            dataLayer.push({'event': 'UserRegistration'});
        })();
    </script>
{% endblock alert_message %}

genoome/accounts/templates/user_profile.html
{% extends 'base.html' %}

{% block title %}Your profile{% endblock title %}
{% block page_title %}Your profile{% endblock page_title %}

{% block content %}
    <section class="section">
        <div class="container">

            <div class="row">
                <div class="col-md-6 col-sm-12 col-xs-12 col-md-offset-3">

                    {% if is_admin %}
                    <div class="alert alert-warning" role="alert"><strong>Warning!</strong>  You are browsing user data from admin</div>
                    {% endif %}

                    <div class="text-content">

                        <ul class="unstyled">
                            {% if request.user.can_upload_files %}
                            <li>
                                <a href="{% url "disease:upload_genome" %}">
                                <i class="fa fa-upload" aria-hidden="true"></i> Upload your genome
                                </a>
                            </li>
                            {% endif %}
                            <li>
                                <a href="{% url 'accounts:disable' %}">
                                    <i class="fa fa-times" aria-hidden="true"></i> Disable account
                                </a>
                            </li>
                        </ul>

                        {% if saved_genome_data %}
                        <p>By clicking on items below you can browse previously uploaded data.</p>
                        {% endif %}
                        <div class="list-group">
                            {% for row in saved_genome_data %}
                            <a href="{% url "disease:browse_genome" %}?file={{ row|urlencode }}{% if is_admin %}&pk={{ user_pk }}{% endif %}" class="list-group-item">
                            <i class="fa fa-database" aria-hidden="true"></i> {{ row }}
                            </a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}