genoome/disease/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.core.urlresolvers import reverse_lazy

from . import views

urlpatterns = [
    url(r'^upload/$', views.UploadGenome.as_view(), name='upload_genome'),
    url(r'^upload-success/(?P<pk>[0-9]+)/$', csrf_exempt(login_required(views.UploadGenomeSuccessView.as_view(), login_url=reverse_lazy('accounts:signin'))), name='upload_success'),
    url(r'^browse/$', login_required(views.DisplayGenomeResult.as_view(), login_url=reverse_lazy('accounts:signin')), name='browse_genome'),
    url(r'^landing-genome-data/$', views.landing_genome_data, name='landing_json_data'),
    url(r'^description/(?P<pk>[0-9]+)/$', views.allele_description, name='description'),
    url(r'^payment-status/$', csrf_exempt(views.PaymentStatusView.as_view()), name='payment_status'),
]

genoome/genoome/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.contrib.flatpages.views import flatpage
from django_markdown import flatpages

from accounts.views import LandingView
from disease.views import upload_progress

admin.autodiscover()
flatpages.register()

urlpatterns = patterns('',
    url(r'^$', LandingView.as_view(), name='landing_page'),
    url(r'^faq/$', TemplateView.as_view(template_name='faq.html'), name='faq'),
    url(r'^genotype-description', flatpage, name='genotype_description'),

    # Examples:
    # url(r'^$', 'genoome.views.home', name='home'),
    url(r'^update-progress/$', upload_progress, name='upload_progress'),
    url(r'^disease/', include('disease.urls', namespace='disease')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^payments/', include('payments.urls', namespace='payments')),
    url(r'^23andme/', include('twentythree.urls', namespace='23andme')),

    url('^markdown/', include('django_markdown.urls')),


    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

# Uncomment the next line to serve media files in dev.
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

genoome/payments/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
import payments.signals  # noqa

from . import views

urlpatterns = [
    url(r'^paypal-callback/', include('paypal.standard.ipn.urls'),
        name='paypal_callback'),
    url(r'^redeem_coupon/$', login_required(views.CouponPaymentView.as_view()), name='redeem_coupon'),
]

genoome/twentythree/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.login23, name='login'),
    url(r'^comeback/$', views.comeback, name='comeback'),
    url(r'^profiles/$', views.profiles, name='profiles'),
    url(r'^status/$', views.status, name='status'),
]

genoome/disease/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os

from django import forms
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.contrib.auth import get_user_model

from disease.files_utils import get_genome_filepath

storage = FileSystemStorage()

class UploadGenomeForm(forms.Form):
    file = forms.FileField()

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        if not self.user.is_authenticated():
            self.fields['email'] = forms.EmailField()

    def clean_file(self):
        if self.user.is_authenticated() and not self.user.can_upload_files:
            raise forms.ValidationError('You already have uploaded genome file.', 'invalid')

        raw_file = self.cleaned_data.get('file', None)
        raw_filename = getattr(raw_file, 'name', None)
        if self.user.is_authenticated() and storage.exists(get_genome_filepath(self.user, raw_filename)):
            raise forms.ValidationError('You have already uploaded this file', 'invalid')
        if len(raw_filename.rsplit('.', 1)) != 2:
            raise forms.ValidationError('Provide file with correct extension', 'invalid')
        return self.cleaned_data['file']

    def clean_email(self):
        if self.fields.get('email', None) is None:  # Happens when user is not logged in
            return None
        email = self.cleaned_data.get('email', None)
        user_model = get_user_model()
        try:
            user = user_model.objects.get(email=email)
            can_upload = user.can_upload_files
        except user_model.DoesNotExist:
            can_upload = True  # Assume that new user can upload files
        if not can_upload:
            raise forms.ValidationError('You can not upload more files', 'invalid')
        return email

genoome/disease/views.py
from io import BytesIO
import json
import logging
import uuid
import os

from celery import uuid as celery_uuid
from celery.result import AsyncResult
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth import login
from django.contrib import messages
from django.core.cache import cache
from django.core.urlresolvers import reverse_lazy
from django.core.files.storage import FileSystemStorage
from django.http import JsonResponse, HttpResponseServerError
from django.http import HttpResponse
from django.http import Http404
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.views.generic import FormView
from django.views.generic.edit import ProcessFormView
from django.views.generic import TemplateView
from django.utils import timezone
import msgpack

from paypal.standard.forms import PayPalPaymentsForm

from disease.files_utils import process_filename
from disease.files_utils import get_genome_data as _get_genome_data
from disease.files_utils import get_genome_dirpath
from disease.files_utils import get_genome_filepath
from .models import CustomizedTag
from .forms import UploadGenomeForm
from .models import AnalyzeDataOrder
from .models import AlleleColor
from .models import SNPMarker
from .models import SNPMarkerArticle
from .tasks import recompute_genome_file

log = logging.getLogger(__name__)

storage = FileSystemStorage()

def upload_progress(request):
    """
    Return JSON object with information about the progress of an upload.
    """
    progress_id = ''
    if 'X-Progress-ID' in request.GET:
        progress_id = request.GET['X-Progress-ID']
    elif 'X-Progress-ID' in request.META:
        progress_id = request.META['X-Progress-ID']
    if progress_id:
        cache_key = "%s_%s" % (request.META['REMOTE_ADDR'], progress_id)
        data = cache.get(cache_key)
        log.debug('PID: %s, Upload progress cache %s',os.getpid(),  data)
        if data is None:
            data = {'length': 1, 'uploaded': 1}
        return JsonResponse(data)
    else:
        return HttpResponseServerError('Server Error: You must provide X-Progress-ID header or query param.')


class GenomeFilePathMixin(object):

    def process_filename(self, filename, filename_suffix=None):
        return process_filename(filename, filename_suffix)

    def get_dirpath(self, user=None):
        if user is None:
            user = self.request.user
        return get_genome_dirpath(user)

    def get_filepath(self, filename, user=None):
        if user is None:
            user = self.request.user
        return get_genome_filepath(user, filename)


class JSONResponseMixin(object):
    """
    A mixin that can be used to render a JSON response.
    """
    def render_to_json_response(self, context, **response_kwargs):
        """
        Returns a JSON response, transforming 'context' to make the payload.
        """
        return JsonResponse(
            self.get_data(context),
            **response_kwargs
        )

    def get_data(self, context):
        return context


class UploadGenome(GenomeFilePathMixin, FormView):
    template_name = 'upload_genome.html'
    form_class = UploadGenomeForm
    # success_url = reverse_lazy('disease:upload_success')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get(self, request, *args, **kwargs):
        """
        Handles GET requests and instantiates a blank version of the form.
        """
        form = self.get_form()
        upload_id = uuid.uuid4()
        return self.render_to_response(self.get_context_data(form=form, upload_id=upload_id))

    def save_processed_data(self, data):
        buffer = BytesIO()
        pickle.dump(data, buffer)
        filename = self.process_filename(self.request.FILES['file'].name, filename_suffix='_processed')
        storage.save(self.get_filepath(filename), buffer)

    def get_success_url(self):
        return reverse_lazy('disease:upload_success', kwargs={'pk': self.analyze_order_pk})

    def form_valid(self, form):
        # save file
        # create AnalyzeFileOrder
        # raw_filepath = self.get_filepath(raw_filename)
        cd = form.cleaned_data
        email = cd.get('email', None)
        raw_file = cd.get('file', None)
        raw_filename = getattr(raw_file, 'name', None)
        user_model = get_user_model()
        if not self.request.user.is_authenticated():
            try:
                user = user_model.objects.get(email=email)
            except user_model.DoesNotExist:  # user doesn't have an account, create one
                user = user_model(email=email, username=email)
                user.save()

                # Dirty hack to allow user login by model
                user.backend = 'django.contrib.auth.backends.ModelBackend'
                login(self.request, user)

            # Dirty hack to fix some parts requiring request.user...
            self.request.user = user
        else:
            user = self.request.user

        storage.save(self.get_filepath(raw_filename, user=user), raw_file)
        task_id = celery_uuid()
        analyze_order = AnalyzeDataOrder(uploaded_filename=raw_filename, user=user, task_uuid=task_id)

        if user.is_staff and user.is_active:
            log.info('User %s skipping payment due to staff membership', user)
            analyze_order.paid = timezone.now()
        analyze_order.save()
        recompute_genome_file.apply_async(args=(self.get_filepath(raw_filename, user=user),),
                                          task_id=task_id)
        # table = process_genoome_data(data)
        # file_exists = os.path.isfile(os.path.join(settings.MEDIA_ROOT, self.get_filepath(self.process_filename(raw_filename, filename_suffix='_processed'))))
        # if self.request.user.is_authenticated() and not file_exists:
        #     self.save_processed_data(table)

        # ctx = self.get_context_data(form=form, table=table, analyzed=True)
        self.analyze_order_pk = analyze_order.pk
        return super().form_valid(form)


def allele_description(request, pk):
    """
    login_required
    user should be able to view only his files
    """
    allele = request.GET['allele']
    marker = get_object_or_404(SNPMarker, pk=pk)
    try:
        article = get_object_or_404(SNPMarkerArticle, snp_marker=marker)
    except Http404:
        return redirect(marker.link)
    colours = AlleleColor.objects.filter(snp_marker=marker)
    your_allele = colours.get(allele=allele)
    ctx = {
        'marker': marker,
        'article': article,
        'colors': colours,
        'your_allele': your_allele,
        'base_template': 'base.html',
    }
    if 'ajax' in request.REQUEST:
        ctx['base_template'] = 'allele_ajax.html'
    return render(request, 'allele_description.html', ctx)


class UploadGenomeSuccessView(TemplateView):
    template_name = 'upload_success.html'

    def post(self, *args, **kwargs):
        return self.get(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        self.analyze_data_order = AnalyzeDataOrder.objects.get(pk=kwargs['pk'])
        user = request.user
        if self.analyze_data_order.is_paid or (user.is_staff and user.is_active):
            return redirect('{}?file={}'.format(reverse_lazy('disease:browse_genome'),
                                                self.analyze_data_order.uploaded_filename))
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        kwargs.update(dict(bitpay_checkout_url=settings.BITPAY_API,
                           analyze_order=self.analyze_data_order,
                           paypal_form=PayPalPaymentsForm(
                               initial=self.analyze_data_order.paypal_data(self.request))
                           ))
        return super().get_context_data(**kwargs)


class DisplayGenomeResult(JSONResponseMixin, GenomeFilePathMixin, TemplateView):
    template_name = 'display_genome_result.html'

    def get(self, request, *args, **kwargs):
        self.user = self.request.user
        if self.is_browsing_via_admin:
            self.user = get_user_model().objects.get(pk=int(self.request.GET['pk']))
        return super().get(request, *args, **kwargs)

    def get_genome_data(self):
        filename = self.process_filename(self.request.GET['file'], filename_suffix='_processed')
        filepath = self.get_filepath(filename)
        data = _get_genome_data(filepath)
        data = list(reversed(sorted(data, key=lambda r: r.get('priority', -1))))
        return data

    @property
    def is_admin(self):  # TODO use permissions?
        return bool(self.request.user.is_staff and self.request.user.is_active)

    @property
    def is_browsing_via_admin(self):
        return bool(('pk' in self.request.GET) and self.is_admin)

    def get_filepath(self, filename):
        if self.is_browsing_via_admin:
            return get_genome_filepath(self.user, filename)
        return super().get_filepath(filename)

    def get_analyze_data_order(self):
        order_kwargs = dict(uploaded_filename=self.request.GET['file'], user=self.user)
        try:
            analyze_data_order = AnalyzeDataOrder.objects.get(**order_kwargs)
        except AnalyzeDataOrder.DoesNotExist:
            if not self.is_browsing_via_admin:
                analyze_data_order = AnalyzeDataOrder(**order_kwargs)
                analyze_data_order.save()
        return analyze_data_order

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['allele_tags'] = CustomizedTag.objects.filter(show_on_data=True)
        ctx['is_admin'] = is_admin = self.is_admin

        analyze_data_order = self.get_analyze_data_order()
        paid = analyze_data_order.is_paid

        job = AsyncResult(analyze_data_order.task_uuid)

genoome/disease/templates/includes/color_legend.html
{% for legend_row in legend_rows %}
    <span class="label label-tag" style="background-color: {{ legend_row.color.color }}" data-val="{{ legend_row.color.color }}">
        <span class="label-inside">{{ legend_row.content }}</span>
    </span>
{% endfor %}

genoome/disease/templates/includes/data_table.html
{% load disease_tags %}
<div class="tags">
	<div class="heading">Display traits that are:</div>
	<div id="genome-labels" class="genome-labels">
    {% color_legend %}
	</div>

	<div class="heading">and relate to:</div>
	<div id="genome-tags" class="genome-tags">
		{% for tag in allele_tags %}
		<span class="label label-default" style="background-color: {{ tag.color_on }}" data-val="{{ tag.slug }}">
			<span class="label-inside">{{ tag.slug }}</span>
		</span>
		{% endfor %}
	</div>

	<div class="row">
		<div class="col-sm-3">
			<label for="genome-search" class="heading">filter by:</label>
			<input id="genome-search" type="search" class="form-control" placeholder="keyword" aria-controls="genomeData">
		</div>
	</div>
</div>

<div class="viewing-options form-inline">
	<div class="form-group">
		<label for="show">Show</label>
		<select id="show" name="genomeData_length" aria-controls="genomeData" class="form-control">
			<option value="10">10</option>
			<option value="30" selected="selected">30</option>
			<option value="50">50</option>
			<option value="100">100</option>
		</select> entries
	</div>
	<div class="form-group">
		<label for="sort">Sort by</label>
		<select id="sort" name="sort" aria-controls="genomeData" class="form-control">
			<option value="">- choose -</option>
			<option value="rsid" data-type="number">Rsid</option>
			<option value="chromosome_position" data-type="number">Chromosome pos.</option>
			<option value="risk_allele" data-type="string">Risk Allele</option>
			<option value="genotype" data-type="string">Genotype</option>
			<option value="disease_trait" data-type="string">Disease Trait</option>
			<option value="p_value" data-type="number">P value</option>
			<option value="or_or_beta" data-type="number">OR</option>
			<option value="risk" data-type="number">Risk</option>
			<option value="priority" data-type="number">Priority</option>
			<option value="tags" data-type="array">Tags</option>
		</select>
	</div>
</div>

<div id="genome-listing" class="accordion genome-listing" data-genome-url="{{ genome_data_url }}">
	<div class="loading">Processing...</div>
</div>

<div id="genome-navigation" class="row">
	<div class="col-sm-3">
		<div class="page-counter" role="status" aria-live="polite"></div>
	</div>
	<div class="col-sm-9">
		<ul class="pagination"></ul>
	</div>
</div>

    {#    <tbody>#}
    {#    {% for row in table %}#}
    {#        <tr data-url="{{ row.link }}?allele={{ row.genotype }}" {% if row.color %}style="background-color: {{ row.color }}"{% endif %}>#}
    {#            <td>{{ row.rsid }}</td>#}
    {#            <td>{{ row.chromosome_position }}</td>#}
    {#            <td>{{ row.risk_allele }}</td>#}
    {#            <td>{{ row.genotype }}</td>#}
    {#            <td>{{ row.disease_trait }}</td>#}
    {#            <td>{{ row.p_value }}</td>#}
    {#            <td>{{ row.or_or_beta }}</td>#}
    {#            <td>{{ row.risk }}</td>#}
    {#            <td>{{ row.priority|default:0 }}</td>#}
    {#            <td>{% for tag in row.tags %}{{ tag }}{% if not forloop.last %};{% endif %}{% endfor %}</td>#}
    {#            <td>{{ row.color }}</td>#}
    {#        </tr>#}
    {#    {% endfor %}#}
    {#    </tbody>#}

genoome/disease/templates/includes/payment_button.html
<div class="text-center payment-choices" data-tid="{{ analyze_order.pk }}" data-sku="{{ analyze_order.uploaded_filename }}">
    <div class="row">

        <div class="col-md-12 payment-choice payment-paypal">
            {{ paypal_form.render }}
        </div>

        <div class="col-md-5 col-md-offset-1 payment-choice payment-bitpay">
            <form action="{{ bitpay_checkout_url }}/checkout" method="post" >
                <input type="hidden" name="action" value="checkout" />
                <input type="hidden" name="posData" value="{{ analyze_order.posData }}" />
                <input type="hidden" name="data" value="b/EqsuWucDOtIz59WzCgRjZk6b/fJ1/a7cKOxJXs9Bvx66fqRI/QvpN0oLoOdnn8C0D3tZPZp9r2Pssjtx+2Xi37MYD6NMjt6bd64hSeTSGTSXO1HHFcDdkE9W3cq7uvweltodaKlWIE/6RMkZjmsaikcYBox2B8IMsTy2e3jkRo/dPy5u0ppxg2w7Qz/ntblu2jir4ve8zSq1Ogqgk0z9IBSjKY7s6xdR9dXWNdoGbOpeXx/R60A8TTLHbA76mXSMsyBufEcDnA+AeCE2njLJDmnHdEvYvAr0mS7L4eJjZlrlOJgbMMbnX2DjsEX6hVXPqvdH71Z67OxQiUPjxTeqtBpVVCrp+Bb1exDsw74eI=" />
                <input class="btn btn-primary" type="submit" value="Pay using Bitcoin" />
            </form>
        </div>

        <div class="col-md-5 payment-choice payment-coupon">
            <a class="btn btn-primary" href="{% url "payments:redeem_coupon" %}?order_id={{ analyze_order.pk }}">Use coupon code</a>
        </div>
    </div>
</div>

genoome/disease/templates/includes/upload_genome_form.html
{% extends 'generic_form.html' %}
{% block form_action %}{% url "disease:upload_genome" %}?X-Progress-ID={{ upload_id }}{% endblock form_action %}
{% block additional_attributes %}enctype="multipart/form-data" id="upload_form"{% endblock additional_attributes %}
{% block form_fields %}
    {{ block.super }}
{#     <input type="hidden" id="X-Progress-ID" name="X-Progress-ID" value="{{ upload_id }}"/>#}
{% endblock form_fields %}

{% block submit_button %}
    <input class="btn btn-primary" type="submit" value="Upload your genome" />
    <a class="btn btn-primary " href="{% url "23andme:login" %}">Fetch your genome from 23andme</a>
{% endblock submit_button %}